#!/bin/bash
SERVER='<xmpp server here>'
DIR='./share/'
USER='<xmpp username here>'
PASS='<xmpp password here>'
PORT='53333'
	
CHANNEL='<conference channel here>'
CSERVER='<conference server here>'

java -Xms512M -Xmx2G -jar export/peergroup.jar -jid $USER@$SERVER -pass $PASS -chan $CHANNEL@$CSERVER -P2Pport $PORT -dir $DIR
